# Generated by Django 5.0.1 on 2024-01-16 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0003_artist_saved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='albums',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='songs',
        ),
    ]
