# Generated by Django 5.0.1 on 2024-01-16 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0004_remove_artist_albums_remove_artist_songs'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='nb_album',
            field=models.IntegerField(default=0),
        ),
    ]
