# Generated by Django 5.0.1 on 2024-01-16 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0005_artist_nb_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='deezer_id',
            field=models.IntegerField(unique=True),
        ),
    ]
