# Generated by Django 5.0.1 on 2024-01-16 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_album_saved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='artists',
        ),
    ]
