# Generated by Django 5.0.1 on 2024-01-16 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0005_remove_album_songs_album_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='deezer_id',
            field=models.IntegerField(unique=True),
        ),
    ]
