# Generated by Django 5.0.1 on 2024-01-17 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0006_alter_album_deezer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
