# Generated by Django 5.0.1 on 2024-01-17 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0007_alter_album_name'),
        ('artists', '0006_alter_artist_deezer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='contributors',
            field=models.ManyToManyField(related_name='album_contributors', to='artists.artist'),
        ),
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ManyToManyField(related_name='album_artist', to='artists.artist'),
        ),
    ]
