# Generated by Django 5.0.1 on 2024-01-23 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0008_album_contributors_alter_album_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='contributors',
        ),
    ]
