# Generated by Django 5.0.1 on 2024-01-16 19:39


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='saved',
            field=models.BooleanField(default=False),
        ),
    ]
