# Generated by Django 5.0.1 on 2024-01-16 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_song_saved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='albums',
        ),
        migrations.RemoveField(
            model_name='song',
            name='artists',
        ),
    ]
