# Generated by Django 5.0.1 on 2024-01-16 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0004_song_album_song_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='deezer_id',
            field=models.IntegerField(unique=True),
        ),
    ]
