# Generated by Django 5.0.1 on 2024-01-17 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0005_alter_song_deezer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='deezer_id',
            field=models.PositiveBigIntegerField(unique=True),
        ),
    ]
