# Generated by Django 5.0.1 on 2024-01-17 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0006_alter_artist_deezer_id'),
        ('songs', '0006_alter_song_deezer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='contributors',
            field=models.ManyToManyField(related_name='contributors', to='artists.artist'),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.ManyToManyField(related_name='artist', to='artists.artist'),
        ),
    ]
