# Generated by Django 5.0.1 on 2024-01-23 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0007_song_contributors_alter_song_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='contributors',
        ),
    ]
